<a href="https://colab.research.google.com/github/800zeng/GenAI1/blob/main/dive_deep_to_dl_tf.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
import numpy as np

In [ ]:
# x = t.range(12, dtype=t.float32)
x = tf.range(12,)
x

<tf.Tensor: shape=(12,), dtype=int32, numpy=array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=int32)>

In [ ]:
x .shape

TensorShape([12])

In [ ]:
X = tf.reshape(x, (3,-1))
X

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]], dtype=int32)>

In [ ]:
tf.zeros((2,3,4))

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
tf.ones((2,3,4))

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)>

In [ ]:
tf.random.normal((3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 1.7013    ,  1.112184  , -1.0849292 ,  0.19162767],
       [-1.5255338 ,  1.6822884 ,  1.5571865 , -0.15306692],
       [-1.4645792 , -0.73550975,  0.7717161 , -1.017562  ]],
      dtype=float32)>

In [ ]:
tf.constant([[2,3],[2,3]])

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [2, 3]], dtype=int32)>

In [ ]:
x = tf.constant([1.0, 2, 4, 8])
y = tf.constant([2.0, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y  # **运算符是求幂运算

(<tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 3.,  4.,  6., 10.], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([-1.,  0.,  2.,  6.], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 2.,  4.,  8., 16.], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([0.5, 1. , 2. , 4. ], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 1.,  4., 16., 64.], dtype=float32)>)

In [ ]:
tf.exp(x)

<tf.Tensor: shape=(4,), dtype=float32, numpy=
array([2.7182817e+00, 7.3890562e+00, 5.4598148e+01, 2.9809580e+03],
      dtype=float32)>

In [ ]:
X = tf.reshape(tf.range(12, dtype=tf.float32), (3, 4))
Y = tf.constant([[2.2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1.88]])
tf.concat([X, Y], axis=0), tf.concat([X, Y], axis=1)

(<tf.Tensor: shape=(6, 4), dtype=float32, numpy=
 array([[ 0.  ,  1.  ,  2.  ,  3.  ],
        [ 4.  ,  5.  ,  6.  ,  7.  ],
        [ 8.  ,  9.  , 10.  , 11.  ],
        [ 2.2 ,  1.  ,  4.  ,  3.  ],
        [ 1.  ,  2.  ,  3.  ,  4.  ],
        [ 4.  ,  3.  ,  2.  ,  1.88]], dtype=float32)>,
 <tf.Tensor: shape=(3, 8), dtype=float32, numpy=
 array([[ 0.  ,  1.  ,  2.  ,  3.  ,  2.2 ,  1.  ,  4.  ,  3.  ],
        [ 4.  ,  5.  ,  6.  ,  7.  ,  1.  ,  2.  ,  3.  ,  4.  ],
        [ 8.  ,  9.  , 10.  , 11.  ,  4.  ,  3.  ,  2.  ,  1.88]],
       dtype=float32)>)

In [ ]:
X == Y, X < Y, X.numpy()

(<tf.Tensor: shape=(3, 4), dtype=bool, numpy=
 array([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])>,
 <tf.Tensor: shape=(3, 4), dtype=bool, numpy=
 array([[ True, False,  True, False],
        [False, False, False, False],
        [False, False, False, False]])>,
 array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]], dtype=float32))

# **Linear Algebra**

In [ ]:
# scalar
x = tf.tensor(3.0)
y = tf.tensor(2.0)
x, y, x + y, x * y, x / y, x**y

AttributeError: module 'tensorflow' has no attribute 'tensor'

In [ ]:
# vectors
# For example, if we were training a model to predict the risk of a loan defaulting,
# we might associate each applicant with a vector whose components correspond to quantities like their income,
# length of employment, or number of previous defaults. Vectors are implemented as 1st -order tensors.
x = tf.arange(3)
x

In [ ]:
# indexing, lenth
x[2], len(x), x.shape

In [ ]:
#, Matrices
# A in R(m x n), 2nd order tensor with shape (m, n), m # of rows, n # of cols, When m = n, we say it a square
A = tf.reshape(tf.range(24), (2,3,4))
A, tf.reduce_sum(A)
# this sum will produce a scalar

In [ ]:
# Tensors, 3rd order, axes corresponding to H, W, Channel in image as example, a collection of images is represented as 4th order tensor
X = t.arange(24).reshape(2,3,4)

In [ ]:
a = 2
a + X, (a*X).shape

In [ ]:
# basic arithmetic property o tensor
# element wise addition
A = t.arange(12).reshape(3,4)
B = A.clone()

A, A + B

In [ ]:
# elementwise production.
A*B,

In [ ]:
# matrix multiplication, Amxn * Bnxk = Cmxk


In [ ]:
a = t.ones((2, 5, 4))
a.shape

In [ ]:
c = a.sum(axis = [0,2])
c

In [ ]:
c = a.sum(axis = 1, keepdims = True)
c

In [ ]:
A = tf.reshape(tf.range(6, dtype=tf.float32), (2, 3))
A

# **reduce sum**

In [ ]:
A.shape, tf.reduce_sum(A)

In [ ]:
A.shape, tf.reduce_sum(A, axis=0)

In [ ]:
sum_A = tf.reduce_sum(A, axis=0, keepdims=True)
sum_A, sum_A.shape

# **Non reduce sum**

In [ ]:
sum_A = tf.reduce_sum(A, axis=1, keepdims=True)
sum_A, sum_A.shape

In [ ]:
A/sum_A

In [ ]:
tf.cumsum(A, axis=0)

# **Dot Products**

In [ ]:
'''So far, we have only performed elementwise operations, sums, and averages. And if this was all we could do, linear algebra would not deserve its own section. Fortunately, this is where things get more interesting. One of the most fundamental operations is the dot product. Given two vectors
, their dot product
 (also known as inner product,
) is a sum over the products of the elements at the same position:
.'''
x = tf.range(3,dtype=tf.float32)
y = tf.ones(3,dtype=tf.float32)
x, y, tf.tensordot(x, y, axes=1)

In [ ]:
# Equivalently, we can calculate the dot product of two vectors by performing an elementwise multiplication followed by a sum:
tf.reduce_sum(x * y)

'''Dot products are useful in a wide range of contexts. For example, given some set of values, denoted by a vector
, and a set of weights, denoted by
, the weighted sum of the values in
 according to the weights
 could be expressed as the dot product
. When the weights are nonnegative and sum to
, i.e.,
, the dot product expresses a weighted average. After normalizing two vectors to have unit length, the dot products express the cosine of the angle between them. Later in this section, we will formally introduce this notion of length.
'''


# **Matrix–Vector Products**

In [ ]:
# tbd

# **Calculus**

In [ ]:
def f(x):
    return 3 * x ** 2 - 4 * x

In [ ]:
for h in 10.0**np.arange(-1, -6, -1):
    print(f'h={h:.5f}, numerical limit={(f(1+h)-f(1))/h:.5f}')

h=0.10000, numerical limit=2.30000
h=0.01000, numerical limit=2.03000
h=0.00100, numerical limit=2.00300
h=0.00010, numerical limit=2.00030
h=0.00001, numerical limit=2.00003


In [ ]:
np.arange(-6, -1, 1)

array([-6, -5, -4, -3, -2])