<a href="https://colab.research.google.com/github/800zeng/GenAI1/blob/main/Dive_deep_to_DL_Torch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np

# **Numpy vs. Pytorch to get computation graph**

In [ ]:
np.random.seed(0)
N, D = 3, 4
x = np.random.randn(N, D)
y = np.random.randn(N, D)
z = np.random.randn(N, D)
x, y, z

(array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ],
        [ 1.86755799, -0.97727788,  0.95008842, -0.15135721],
        [-0.10321885,  0.4105985 ,  0.14404357,  1.45427351]]),
 array([[ 0.76103773,  0.12167502,  0.44386323,  0.33367433],
        [ 1.49407907, -0.20515826,  0.3130677 , -0.85409574],
        [-2.55298982,  0.6536186 ,  0.8644362 , -0.74216502]]),
 array([[ 2.26975462, -1.45436567,  0.04575852, -0.18718385],
        [ 1.53277921,  1.46935877,  0.15494743,  0.37816252],
        [-0.88778575, -1.98079647, -0.34791215,  0.15634897]]))

In [ ]:
a = x * y
b = a + z
c = np.sum(b)
a, b, c

(array([[ 1.34251038,  0.04868913,  0.43442581,  0.74772853],
        [ 2.79027931,  0.20049663,  0.297442  ,  0.12927355],
        [ 0.26351668,  0.26837482,  0.12451648, -1.07931093]]),
 array([[ 3.61226501, -1.40567654,  0.48018432,  0.56054468],
        [ 4.32305853,  1.6698554 ,  0.45238942,  0.50743607],
        [-0.62426907, -1.71242165, -0.22339567, -0.92296196]]),
 6.717008537800067)

In [ ]:
grad_c = 1
grad_b = grad_c * np.ones((N, D))
grad_a = grad_b.copy()
grad_z = grad_b.copy()
grad_x = grad_a * y
grad_y = grad_a * x
print('grand_b', grad_b, 'grand_a', grad_a, 'grand_z', grad_z, 'grand_x', grad_x, 'grand_y', grad_y)

grand_b [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] grand_a [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] grand_z [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] grand_x [[ 0.76103773  0.12167502  0.44386323  0.33367433]
 [ 1.49407907 -0.20515826  0.3130677  -0.85409574]
 [-2.55298982  0.6536186   0.8644362  -0.74216502]] grand_y [[ 1.76405235  0.40015721  0.97873798  2.2408932 ]
 [ 1.86755799 -0.97727788  0.95008842 -0.15135721]
 [-0.10321885  0.4105985   0.14404357  1.45427351]]


In [ ]:
# TROCH
N, D = 3, 4
x = torch.randn(N, D, requires_grad=True)
y = torch.randn(N, D, requires_grad=True)
z = torch.randn(N, D, requires_grad=True)
x, y, z

(tensor([[-0.6316,  0.0711, -1.0862,  0.0627],
         [ 1.0462,  1.7559,  0.8001, -0.4680],
         [ 1.1423,  0.5165,  0.8130,  1.6144]], requires_grad=True),
 tensor([[ 1.0043,  0.8696,  0.0918,  1.5185],
         [-1.0776, -0.1524, -0.5951,  0.2018],
         [ 0.8187,  1.0242,  0.4863, -0.1448]], requires_grad=True),
 tensor([[ 0.9381, -0.3624,  0.7494, -0.0773],
         [-0.1627, -0.9731,  0.6774,  0.2538],
         [-0.3949, -0.0471,  0.3408, -1.4254]], requires_grad=True))

In [ ]:
a = x * y
b = a + z
c = torch.sum(b)
a, b, c

(tensor([[-0.6343,  0.0618, -0.0997,  0.0952],
         [-1.1274, -0.2676, -0.4761, -0.0945],
         [ 0.9352,  0.5290,  0.3954, -0.2338]], grad_fn=<MulBackward0>),
 tensor([[ 0.3039, -0.3006,  0.6496,  0.0179],
         [-1.2901, -1.2407,  0.2012,  0.1594],
         [ 0.5403,  0.4820,  0.7362, -1.6592]], grad_fn=<AddBackward0>),
 tensor(-1.4001, grad_fn=<SumBackward0>))

In [ ]:
c.backward()
print(x.grad, y.grad, z.grad)

tensor([[ 1.0043,  0.8696,  0.0918,  1.5185],
        [-1.0776, -0.1524, -0.5951,  0.2018],
        [ 0.8187,  1.0242,  0.4863, -0.1448]]) tensor([[-0.6316,  0.0711, -1.0862,  0.0627],
        [ 1.0462,  1.7559,  0.8001, -0.4680],
        [ 1.1423,  0.5165,  0.8130,  1.6144]]) tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


Let’s assume that we are interested in differentiating the function 2x^2
 with respect to the column vector
. To start, we assign x an initial value.

In [ ]:
x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [ ]:
x.requires_grad_(True)  # Same as `x = torch.arange(4.0, requires_grad=True)`
x.grad # the grad is None by default

In [ ]:
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

In [ ]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [ ]:
# We already know that the gradient of the function 2*(x**2)
#  with respect to
#  should be
x.grad == 4 * x

tensor([True, True, True, True])

In [ ]:
# /****Now let’s calculate another function of x and take its gradient.
#  Note that PyTorch does not automatically reset the gradient buffer when we record a new gradient.
#  Instead, the new gradient is added to the already-stored gradient. This behavior comes in handy
#  when we want to optimize the sum of multiple objective functions. To reset the gradient buffer, we can call x.grad.zero_() as follows:

x.grad.zero_()
y = 2*x.sum()
y.backward()
x.grad

tensor([2., 2., 2., 2.])

In [ ]:
y = x.sum()
y

tensor(6., grad_fn=<SumBackward0>)

In [ ]:
x, x.shape

(tensor([0., 1., 2., 3.], requires_grad=True), torch.Size([4]))

In [ ]:
x1 = torch.rand(1,2)
x1.shape

torch.Size([1, 2])

In [ ]:
torch.transpose(x1,0,1)

tensor([[0.3419],
        [0.7301]])

In [ ]:
x.shape

torch.Size([4])